   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*             CLIPS Version 6.40  07/30/16            */
   /*                                                     */
   /*              FACT FUNCTIONS HEADER FILE             */
   /*******************************************************/

/*************************************************************/
/* Purpose:                                                  */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Gary D. Riley                                        */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*                                                           */
/*      6.23: Correction for FalseSymbol/TrueSymbol. DR0859  */
/*                                                           */
/*            Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*      6.24: Added ppfact function.                         */
/*                                                           */
/*      6.30: Support for long long integers.                */
/*                                                           */
/*            Removed conditional code for unsupported       */
/*            compilers/operating systems (IBM_MCW,          */
/*            MAC_MCW, and IBM_TBC).                         */
/*                                                           */
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*            Converted API macros to function calls.        */
/*                                                           */
/*      6.40: Removed LOCALE definition.                     */
/*                                                           */
/*            Pragma once and other inclusion changes.       */
/*                                                           */
/*            Added support for booleans with <stdbool.h>.   */
/*                                                           */
/*            Removed use of void pointers for specific      */
/*            data structures.                               */
/*                                                           */
/*************************************************************/

#ifndef _H_factfun

#pragma once

#define _H_factfun

#include "factmngr.h"

   void                           FactFunctionDefinitions(Environment *);
   void                           FactRelationFunction(UDFContext *,CLIPSValue *);
   struct symbolHashNode         *FactRelation(Fact *);
   Deftemplate                   *EnvFactDeftemplate(Environment *,Fact *);
   void                           FactExistpFunction(UDFContext *,CLIPSValue *);
   bool                           EnvFactExistp(Environment *,Fact *);
   void                           FactSlotValueFunction(UDFContext *,CLIPSValue *);
   void                           FactSlotValue(Environment *,Fact *,const char *,CLIPSValue *);
   void                           FactSlotNamesFunction(UDFContext *,CLIPSValue *);
   void                           EnvFactSlotNames(Environment *,Fact *,DATA_OBJECT *);
   void                           GetFactListFunction(UDFContext *,CLIPSValue *);
   void                           EnvGetFactList(Environment *,DATA_OBJECT *,Defmodule *);
   void                           PPFactFunction(UDFContext *,CLIPSValue *);
   void                           EnvPPFact(Environment *,Fact *,const char *,bool);
   struct fact                   *GetFactAddressOrIndexArgument(UDFContext *,bool);

#endif /* _H_factfun */

