   /*******************************************************/
   /*      "C" Language Integrated Production System      */
   /*                                                     */
   /*            CLIPS Version 6.40  01/06/16             */
   /*                                                     */
   /*          MISCELLANEOUS FUNCTIONS HEADER FILE        */
   /*******************************************************/

/*************************************************************/
/* Purpose:                                                  */
/*                                                           */
/* Principal Programmer(s):                                  */
/*      Gary D. Riley                                        */
/*                                                           */
/* Contributing Programmer(s):                               */
/*                                                           */
/* Revision History:                                         */
/*                                                           */
/*      6.23: Correction for FalseSymbol/TrueSymbol. DR0859  */
/*                                                           */
/*            Corrected compilation errors for files         */
/*            generated by constructs-to-c. DR0861           */
/*                                                           */
/*            Changed name of variable exp to theExp         */
/*            because of Unix compiler warnings of shadowed  */
/*            definitions.                                   */
/*                                                           */
/*      6.24: Removed CONFLICT_RESOLUTION_STRATEGIES,        */
/*            DYNAMIC_SALIENCE, INCREMENTAL_RESET,           */
/*            LOGICAL_DEPENDENCIES, IMPERATIVE_METHODS       */
/*            INSTANCE_PATTERN_MATCHING,                     */
/*            IMPERATIVE_MESSAGE_HANDLERS, and               */
/*            AUXILIARY_MESSAGE_HANDLERS compilation flags.  */
/*                                                           */
/*            Renamed BOOLEAN macro type to intBool.         */
/*                                                           */
/*      6.30: Support for long long integers.                */
/*                                                           */
/*            Used gensprintf instead of sprintf.            */
/*                                                           */
/*            Removed conditional code for unsupported       */
/*            compilers/operating systems.                   */
/*                                                           */
/*            Renamed EX_MATH compiler flag to               */
/*            EXTENDED_MATH_FUNCTIONS.                       */
/*                                                           */
/*            Combined BASIC_IO and EXT_IO compilation       */
/*            flags into the IO_FUNCTIONS compilation flag.  */
/*                                                           */    
/*            Removed code associated with HELP_FUNCTIONS    */
/*            and EMACS_EDITOR compiler flags.               */
/*                                                           */    
/*            Added operating-system function.               */
/*                                                           */ 
/*            Added new function (for future use).           */
/*                                                           */ 
/*            Added const qualifiers to remove C++           */
/*            deprecation warnings.                          */
/*                                                           */
/*      6.40: Refactored code to reduce header dependencies  */
/*            in sysdep.c.                                   */
/*                                                           */
/*            Fact ?var:slot reference support.              */
/*                                                           */
/*            Added local-time and gm-time functions.        */
/*                                                           */
/*************************************************************/

#ifndef _H_miscfun

#pragma once

#define _H_miscfun

   void                           MiscFunctionDefinitions(void *);
   void                           CreateFunction(void *,DATA_OBJECT_PTR);
   void                           SetgenFunction(UDFContext *,CLIPSValue *);
   void                           GensymFunction(UDFContext *,CLIPSValue *);
   void                           GensymStarFunction(UDFContext *,CLIPSValue *);
   long long                      RandomFunction(void *);
   void                           SeedFunction(void *);
   long long                      LengthFunction(void *);
   void                           ConserveMemCommand(void *);
   long long                      ReleaseMemCommand(void *);
   long long                      MemUsedCommand(void *);
   long long                      MemRequestsCommand(void *);
   void                           OptionsCommand(UDFContext *,CLIPSValue *);
   void                          *OperatingSystemFunction(void *);
   void                           ExpandFuncCall(void *,DATA_OBJECT *);
   void                           DummyExpandFuncMultifield(void *,DATA_OBJECT *);
   void                          *CauseEvaluationError(void *);
   bool                           SetSORCommand(void *);
   void                          *GetFunctionRestrictions(void *);
   void                           AproposCommand(void *);
   void                           GensymStar(void *,CLIPSValue *);
   void                           GetFunctionListFunction(void *,DATA_OBJECT *);
   void                           FuncallFunction(void *,DATA_OBJECT *);
   void                           NewFunction(void *,DATA_OBJECT *);
   void                           CallFunction(void *,DATA_OBJECT *);
   double                         TimerFunction(void *);
   double                         TimeFunction(void *);
   void                           SystemCommand(void *);
   void                           SlotValueFunction(void *,DATA_OBJECT *);
   void                           LocalTimeFunction(void *,DATA_OBJECT *);
   void                           GMTimeFunction(void *,DATA_OBJECT *);

#endif /* _H_miscfun */






